### ISSUE TITLE
Vertical Pipe Entrances Should be Offset A Bit

### ISSUE THREAD

**Issue by Yoshifanatic1** [Yoshimaster96/Superstar-Editor-SMW#7]
Entrance position objects that are set to one of the vertical pipe entrance actions should be offset to the right by 8 pixels, so that their position matches where Mario shows up in game.

![Untitled](https://user-images.githubusercontent.com/60048201/91915195-e2523580-ec87-11ea-92c9-af3cddb0f6f6.png)

**Comment by Yoshimaster96** [comment]
I knew about that, but I haven't gotten around to fixing it. I'll do it right now. Thanks for reminding me!
