### ISSUE TITLE
Enabling Animations Makes the Editor Lag Significantly

### ISSUE THREAD

**Issue by Yoshifanatic1** [Yoshimaster96/Superstar-Editor-SMW#8]
If animations are enabled, the editor gets noticeably more laggy. I have a pretty good mid-range computer that has no trouble running intensive things, like BSNES in Accuracy mode, so something about the way the editor handles animations is not very well optimized. For comparison, my computer has no issue running Lunar Magic with 60 FPS animations enabled.

**Comment by Yoshimaster96** [comment]
Yeah, this one has been bugging me for a while. I honestly have no clue what to do about it.

**Comment by Yoshimaster96** [comment]
Finally figured this one out. Should be fixed now.
